name: CI-Build-Push-Update-Manifests

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write   # allow the workflow to commit back to the repo

jobs:
  build-publish-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push image
        run: |
          IMAGE=juvard/nginx-demo:${{ steps.vars.outputs.TAG }}
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Update deployment image tag
        run: |
          yq -i '
            (.spec.template.spec.containers[] | select(.name=="nginx") | .image) = env(IMAGE)
          ' k8s/deployment.yaml

      - name: Commit & push manifest change
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "CI: update image to $IMAGE" || echo "No changes to commit"
          git push
